USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE  RIPPAA_MIGRATION;
USE SCHEMA    RIPPAA_MIGRATION.REF;

-- POA → postcode → region/state from ABS
-- Confirm this table exists in your account (names must match your share):
-- GEOGRAPHY__BOUNDARIES__INSIGHTS__AUSTRALIA.GEOGRAPHY_AUS_FREE.ABS_POA_2021_AUST_GDA2020

CREATE VIEW REGION_MAPPING AS
SELECT
  LPAD(TO_VARCHAR(POA_CODE_2021), 4, '0') AS POSTCODE,
  POA_CODE_2021                           AS POA_CODE,
  POA_NAME_2021                           AS POA_NAME,
  STATE_NAME_2021                         AS STATE_NAME
FROM GEOGRAPHY__BOUNDARIES__INSIGHTS__AUSTRALIA.GEOGRAPHY_AUS_FREE.ABS_POA_2021_AUST_GDA2020;

-- Make sure SYSADMIN can see it (optional if using ACCOUNTADMIN)
GRANT SELECT ON VIEW REGION_MAPPING TO ROLE SYSADMIN;
