USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE  RIPPAA_MIGRATION;
USE SCHEMA    RIPPAA_MIGRATION.SILVER;

-- Base movers view from share (adjust path if your share differs)
-- AUSTRALIA_POST_MOVERS_STATISTICS.AUS_POST.V_MOVERS_STATISTICS

CREATE OR REPLACE VIEW MOVERS_ENRICHED AS
SELECT
  m.STAT_MONTH,
  m.FROM_POSTCODE,
  m.TO_POSTCODE,
  m.NUMBER_OF_ADDRESSES   AS ADDRESSES,

  rf.POA_NAME     AS FROM_REGION,
  rf.STATE_NAME   AS FROM_STATE,

  rt.POA_NAME     AS TO_REGION,
  rt.STATE_NAME   AS TO_STATE

FROM AUSTRALIA_POST_MOVERS_STATISTICS.AUS_POST.V_MOVERS_STATISTICS m
LEFT JOIN RIPPAA_MIGRATION.REF.REGION_MAPPING rf
  ON LPAD(m.FROM_POSTCODE, 4, '0') = rf.POSTCODE
LEFT JOIN RIPPAA_MIGRATION.REF.REGION_MAPPING rt
  ON LPAD(m.TO_POSTCODE,   4, '0') = rt.POSTCODE;

-- Smoke test
-- SELECT * FROM MOVERS_ENRICHED LIMIT 20;
