USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE  RIPPAA_MIGRATION;
USE SCHEMA    RIPPAA_MIGRATION.GOLD;

CREATE OR REPLACE VIEW STATE_MONTHLY_FLOWS AS
SELECT
  STAT_MONTH,
  FROM_STATE,
  TO_STATE,
  SUM(ADDRESSES) AS MOVES,
  SUM(CASE WHEN FROM_STATE <> TO_STATE THEN ADDRESSES ELSE 0 END) AS CROSS_STATE_ADDRESSES
FROM RIPPAA_MIGRATION.SILVER.MOVERS_ENRICHED
GROUP BY 1,2,3;

-- SELECT * FROM STATE_MONTHLY_FLOWS LIMIT 20;
