USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE  RIPPAA_MIGRATION;
USE SCHEMA    RIPPAA_MIGRATION.GOLD;

CREATE OR REPLACE VIEW STATE_OD_MATRIX AS
SELECT
  STAT_MONTH,
  FROM_STATE,
  TO_STATE,
  SUM(ADDRESSES) AS MOVES
FROM RIPPAA_MIGRATION.SILVER.MOVERS_ENRICHED
GROUP BY 1,2,3;
