USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE  RIPPAA_MIGRATION;
USE SCHEMA    RIPPAA_MIGRATION.GOLD;

-- “Suburb” is represented by postcode (POA)
CREATE OR REPLACE VIEW TOP_SUBURB_OD AS
SELECT
  STAT_MONTH,
  FROM_POSTCODE,
  TO_POSTCODE,
  FROM_STATE,
  TO_STATE,
  SUM(ADDRESSES) AS ADDRESSES
FROM RIPPAA_MIGRATION.SILVER.MOVERS_ENRICHED
GROUP BY 1,2,3,4,5;
