USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE  RIPPAA_MIGRATION;

-- keep SYSADMIN productive without breaking current grants
GRANT OWNERSHIP ON SCHEMA RIPPAA_MIGRATION.REF    TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA RIPPAA_MIGRATION.SILVER TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA RIPPAA_MIGRATION.GOLD   TO ROLE SYSADMIN COPY CURRENT GRANTS;

-- Stage for semantic YAML (directory is required by Analyst UI)
USE SCHEMA RIPPAA_MIGRATION.GOLD;

CREATE STAGE IF NOT EXISTS CORTEX_STAGE
  DIRECTORY = ( ENABLE = TRUE );

-- Allow the roles you use in UI to use the stage
GRANT USAGE ON STAGE CORTEX_STAGE TO ROLE SYSADMIN;
GRANT READ  ON STAGE CORTEX_STAGE TO ROLE SYSADMIN;

-- If you prefer PUT via SnowSQL:
--   snowsql -q "PUT file://cortex/MIGRATION_ANALYST.yaml @RIPPAA_MIGRATION.GOLD.CORTEX_STAGE OVERWRITE=TRUE AUTO_COMPRESS=FALSE"
