
---

# 5) SQL – sql/00_init_snowflake.sql

sql
-- Tiny warehouse + medallion database
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS RIPPAA_MIGRATION;
CREATE SCHEMA   IF NOT EXISTS RIPPAA_MIGRATION.REF;
CREATE SCHEMA   IF NOT EXISTS RIPPAA_MIGRATION.SILVER;
CREATE SCHEMA   IF NOT EXISTS RIPPAA_MIGRATION.GOLD;

-- Keep using these everywhere
USE WAREHOUSE COMPUTE_WH;
USE DATABASE  RIPPAA_MIGRATION;
